name: Sync from Upstream

on:
  repository_dispatch:
    types: [sync_from_upstream]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/<OWNER>/<ORIGINAL_REPO>.git
          git fetch upstream
          git merge --ff-only upstream/main || echo "⚠️ 충돌 발생: 수동 해결 필요"
          git push origin HEAD:main
